name:                rsl-language-server
version:             0.1.2.0
github:              "JakuJ/rsl-language-server"
license:             BSD3
author:              "Jakub Janaszkiewicz"
maintainer:          "janaszkiewicz.jakub@gmail.com"
copyright:           "2021 Jakub Janaszkiewicz"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/JakuJ/rsl-language-server#readme>

dependencies:
- base >= 4.7 && < 5
- lsp
- lsp-types
- text
- lens
- process
- megaparsec
- optparse-applicative

default-extensions:
- OverloadedStrings
- DuplicateRecordFields

ghc-options:
  # optimization
  - -flate-dmd-anal
  - -flate-specialise
  # warnings
  - -Wall
  - -Wcompat
  - -Wno-unused-do-bind
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  rsl-language-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options: -O2 -threaded -rtsopts -with-rtsopts=-N
    dependencies:
    - rsl-language-server

tests:
  rsl-language-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-incomplete-uni-patterns
    dependencies:
    - rsl-language-server
    - hspec
    - hspec-discover
    - lsp-test
