name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  stack:
    name: ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install RSLTC
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 texlive-binaries
        sudo dpkg -i CI/rsltc_2.6.1-1_i386.deb
        rsltc -v

    - uses: actions/cache@v2.1.3
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-8.10.5-stack

    - name: Install dependencies
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test --system-ghc

    - name: Prepare binary
      run: |
        zip -j ~/linux.zip "$(stack path --system-ghc --local-install-root)/bin/rsl-language-server"
    
    - uses: actions/upload-artifact@v2
      with:
        name: linux.zip
        path: ~/linux.zip